import { useEffect, useRef } from "react"
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/ScrollTrigger"
import heroBg from "@/assets/hero-bg.png"

gsap.registerPlugin(ScrollTrigger)

const nodes = [
  { id: "01", title: "WhatsApp AI Receptionist", desc: "24/7 multilingual chatbot — books appointments, answers FAQs, qualifies leads." },
  { id: "02", title: "Lead Generation & Qualification", desc: "AI-powered prospecting — finds, filters, and scores leads automatically." },
  { id: "03", title: "CRM & Pipeline Automation", desc: "Syncs leads into your CRM, triggers follow-ups, keeps your pipeline moving." },
  { id: "04", title: "Workflow Automation", desc: "Connects WhatsApp → CRM → Email → SMS → Invoicing into one seamless engine." },
  { id: "05", title: "Review & Reputation", desc: "Automated review requests, smart response drafts, reputation monitoring." },
  { id: "06", title: "AI Analytics & Reporting", desc: "Real-time dashboards generated by AI — no spreadsheets, just clarity." },
]

export function Services() {
  const sectionRef = useRef<HTMLElement>(null)
  const lineRef = useRef<HTMLDivElement>(null)
  const nodeRefs = useRef<(HTMLDivElement | null)[]>([])

  useEffect(() => {
    const ctx = gsap.context(() => {
      // Animate the vertical line drawing down
      gsap.fromTo(
        lineRef.current,
        { scaleY: 0 },
        {
          scaleY: 1,
          ease: "none",
          scrollTrigger: {
            trigger: sectionRef.current,
            start: "top 60%",
            end: "bottom bottom",
            scrub: 0.5,
          },
        }
      )

      // Each node fades in as it scrolls into view
      nodeRefs.current.forEach((el, i) => {
        if (!el) return
        gsap.fromTo(
          el,
          { opacity: 0.1, x: -20 },
          {
            opacity: 1,
            x: 0,
            duration: 0.6,
            scrollTrigger: {
              trigger: el,
              start: "top 80%",
              end: "top 40%",
              scrub: 0.3,
            },
          }
        )
      })
    }, sectionRef)

    return () => ctx.revert()
  }, [])

  return (
    <section ref={sectionRef} id="services" className="relative py-24 md:py-32 overflow-hidden">
      <div
        className="absolute inset-0 bg-cover bg-center bg-fixed opacity-25"
        style={{ backgroundImage: `url(${heroBg})` }}
      />
      <div className="absolute inset-0 bg-[#080c14]/85" />

      <div className="relative max-w-7xl mx-auto px-6 md:px-12">
        <div className="flex items-center gap-4 mb-20">
          <span className="text-xs tracking-[0.3em] uppercase text-[#6b7280] font-medium">Services</span>
          <div className="flex-1 h-px bg-[#1a2035]" />
        </div>

        <h2 className="text-3xl md:text-5xl font-extrabold tracking-tighter text-[#e6e8ed] mb-20">
          Your <span className="text-[#c9a961]">Automation</span> Engine
        </h2>

        {/* Node flow with animated connecting line */}
        <div className="relative max-w-2xl mx-auto lg:mx-0">
          {/* Animated vertical line */}
          <div ref={lineRef} className="absolute left-5 top-0 w-px bg-gradient-to-b from-[#c9a961] via-[#c9a961]/60 to-transparent origin-top" style={{ height: "calc(100% - 40px)" }} />

          {nodes.map((node, i) => (
            <div
              key={node.id}
              ref={(el) => { nodeRefs.current[i] = el }}
              className="relative flex items-start gap-8 pb-16 last:pb-0"
            >
              <div className="w-10 h-10 rounded-full border border-[#c9a961]/40 bg-[#0d1220] flex items-center justify-center text-sm font-bold text-[#c9a961] shrink-0 z-10">
                {node.id}
              </div>
              <div className="pt-1">
                <h3 className="text-lg font-bold text-[#e6e8ed] mb-2">{node.title}</h3>
                <p className="text-sm text-[#6b7280] leading-relaxed max-w-md">{node.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
